# This file is used to autogenerate the travis exclude matrix.
rules:
    "3.5": "NUMPY_VERSION>=1.9.2"
    "3.4": "NUMPY_VERSION>=1.8.1"
    "3.3": "NUMPY_VERSION>=1.7.0,<=1.9.2"
    "3.2": "NUMPY_VERSION==0"
    "2.7": "NUMPY_VERSION>1.5.1"
    "2.6": "NUMPY_VERSION>1.5.1,<=1.9.2"

